TABLA_PARSING = {
    ('<Titulo>', 'Reino'): ['~~', 'Id', 'Muerte', '<Entrada>', '<Procesos>', '<Variables>', '<Tipos>', '<Constantes>', '~', 'Id', 'Reino'],
    ('<Constantes>', 'Reserva'): ['~~', '<Def-constante>', '~', '<Literales>', 'fosil', 'Id', 'Reserva'],
    ('<Constantes>', 'Especies'): ['epsilon'],
    ('<Constantes>', 'Organismos'): ['epsilon'],
    ('<Constantes>', 'Huevos'): ['epsilon'],
    ('<Constantes>', 'Comportamientos'): ['epsilon'],
    ('<Def-constante>', 'Id'): ['<Def-constante>', '~', '<Literales>', 'fosil', 'Id'],
    ('<Def-constante>', '~~'): ['epsilon'],
    ('<Tipos>', 'Especies'): ['~~', '<Def-tipo>', '~', '<Tipos-dec>', 'cripsis', 'Id', 'Especies'],
    ('<Tipos>', 'Organismos'): ['epsilon'],
    ('<Tipos>', 'Huevos'): ['epsilon'],
    ('<Tipos>', 'Comportamientos'): ['epsilon'],
    ('<Def-tipo>', 'Id'): ['<Def-tipo>', '~', '<Tipos-dec>', 'cripsis', 'Id'],
    ('<Def-tipo>', '~~'): ['epsilon'],
    ('<Tipos-dec>', 'Id_tipo_declarado'): ['Id_tipo_declarado'],
    ('<Tipos-dec>', 'Colmena'): ['<Estruc-Dec>'],
    ('<Tipos-dec>', 'Corral'): ['<Estruc-Dec>'],
    ('<Tipos-dec>', 'Quimera'): ['<Estruc-Dec>'],
    ('<Tipos-dec>', 'EOF'): ['<Atomicos>'],
    ('<Variables>', 'Organismos'): ['~~', '<Dec-variable>', '~', '<Var-Cont>', 'Organismos'],
    ('<Variables>', 'Huevos'): ['epsilon'],
    ('<Variables>', 'Comportamientos'): ['epsilon'],
    ('<Var-Cont>', 'Id'): ['<Aux-Var-Cont>', '<Tipo-Habita>', 'habita', '<Identificadores>'],
    ('<Aux-Var-Cont>', '~'): ['epsilon'],
    ('<Aux-Var-Cont>', 'adopta'): ['<Literal-Adopta>', 'adopta'],
    ('<Tipo-Habita>', 'Colmena'): ['Colmena'],
    ('<Tipo-Habita>', 'Corral'): ['Corral'],
    ('<Tipo-Habita>', 'Quimera'): ['Quimera'],
    ('<Tipo-Habita>', 'EOF'): ['<Atomicos>'],
    ('<Literal-Adopta>', 'lit-oveja'): ['<Literales>'],
    ('<Literal-Adopta>', 'lit-huella'): ['<Literales>'],
    ('<Literal-Adopta>', 'lit-serpiente'): ['<Literales>'],
    ('<Literal-Adopta>', 'muerto'): ['<Literales>'],
    ('<Literal-Adopta>', 'vivo'): ['<Literales>'],
    ('<Literal-Adopta>', 'minimo'): ['<Literales>'],
    ('<Literal-Adopta>', 'bajo'): ['<Literales>'],
    ('<Literal-Adopta>', 'medio'): ['<Literales>'],
    ('<Literal-Adopta>', 'alto'): ['<Literales>'],
    ('<Literal-Adopta>', 'maximo'): ['<Literales>'],
    ('<Literal-Adopta>', '{'): ['<Lit-Colmena>'],
    ('<Literal-Adopta>', 'EOF'): ['<Lit-Quimera>'],
    ('<Dec-variable>', '~~'): ['epsilon'],
    ('<Dec-variable>', 'Organismos'): ['~~', '<Dec-variable>', '~', '<Resto-Dec>', 'Organismos'],
    ('<Resto-Dec>', 'Id'): ['<Aux-Resto-Dec>', '<Lugar>', 'habita', '<Identificadores>'],
    ('<Aux-Resto-Dec>', '~'): ['epsilon'],
    ('<Aux-Resto-Dec>', 'adopta'): ['<Literal-Tipo>', 'adopta'],
    ('<Lugar>', 'Colmena'): ['Colmena'],
    ('<Lugar>', 'Corral'): ['Corral'],
    ('<Lugar>', 'Quimera'): ['Quimera'],
    ('<Lugar>', 'EOF'): ['<Atomicos>'],
    ('<Literal-Tipo>', 'lit-oveja'): ['<Literales>'],
    ('<Literal-Tipo>', 'lit-huella'): ['<Literales>'],
    ('<Literal-Tipo>', 'lit-serpiente'): ['<Literales>'],
    ('<Literal-Tipo>', 'muerto'): ['<Literales>'],
    ('<Literal-Tipo>', 'vivo'): ['<Literales>'],
    ('<Literal-Tipo>', 'minimo'): ['<Literales>'],
    ('<Literal-Tipo>', 'bajo'): ['<Literales>'],
    ('<Literal-Tipo>', 'medio'): ['<Literales>'],
    ('<Literal-Tipo>', 'alto'): ['<Literales>'],
    ('<Literal-Tipo>', 'maximo'): ['<Literales>'],
    ('<Literal-Tipo>', '{'): ['<Lit-Colmena>'],
    ('<Literal-Tipo>', 'EOF'): ['<Lit-Quimera>'],
    ('<Procesos>', 'Huevos'): ['<Con-Rutinas>', '<Prototipos>'],
    ('<Procesos>', 'Comportamientos'): ['<Con-Rutinas>', '<Prototipos>'],
    ('<Con-Rutinas>', 'Comportamientos'): ['<Rutinas>'],
    ('<Con-Rutinas>', 'Nacimiento'): ['<Rutinas>'],
    ('<Prototipos>', 'Huevos'): ['~~', '<Aux-Prototipos>', 'Huevos'],
    ('<Prototipos>', 'Comportamientos'): ['epsilon'],
    ('<Aux-Prototipos>', 'entrenar'): ['<Dec-encabezados>', '~', '<Atomicos>', ')', '<Parametros-form>', '(', 'Id', 'entrenar'],
    ('<Aux-Prototipos>', 'ritual'): ['<Dec-encabezados>', '~', ')', '<Parametros-form>', '(', 'Id', 'ritual'],
    ('<Dec-encabezados>', '~~'): ['epsilon'],
    ('<Dec-encabezados>', 'entrenar'): ['<Dec-encabezados>', '~', '<Atomicos>', ')', '<Parametros-form>', '(', 'Id', 'entrenar'],
    ('<Dec-encabezados>', 'ritual'): ['<Dec-encabezados>', '~', ')', '<Parametros-form>', '(', 'Id', 'ritual'],
    ('<Rutinas>', 'Comportamientos'): ['~~', '<Aux-Rutinas>', 'Comportamientos'],
    ('<Rutinas>', 'Nacimiento'): ['epsilon'],
    ('<Aux-Rutinas>', 'entrenar'): ['<Dec-rutinas>', 'delfin', '<Instrucciones>', 'plancton', '~', '<Cuerpo-Entrenar>', 'Id', 'entrenar'],
    ('<Aux-Rutinas>', 'ritual'): ['<Dec-rutinas>', 'delfin', '<Instrucciones>', 'plancton', '~', '<Cuerpo-Ritual>', 'Id', 'ritual'],
    ('<Cuerpo-Entrenar>', '~'): ['epsilon'],
    ('<Cuerpo-Entrenar>', '('): ['<Atomicos>', ')', '<Parametros-form>', '('],
    ('<Cuerpo-Ritual>', '~'): ['epsilon'],
    ('<Cuerpo-Ritual>', '('): [')', '<Parametros-form>', '('],
    ('<Dec-rutinas>', '~~'): ['epsilon'],
    ('<Dec-rutinas>', 'entrenar'): ['<Dec-rutinas>', 'delfin', '<Instrucciones>', 'plancton', '~', '<Cuerpo-Entrenar-Dec>', 'Id', 'entrenar'],
    ('<Dec-rutinas>', 'ritual'): ['<Dec-rutinas>', 'delfin', '<Instrucciones>', 'plancton', '~', '<Cuerpo-Ritual-Dec>', 'Id', 'ritual'],
    ('<Cuerpo-Entrenar-Dec>', '~'): ['epsilon'],
    ('<Cuerpo-Entrenar-Dec>', '('): ['<Atomicos>', ')', '<Parametros-form>', '('],
    ('<Cuerpo-Ritual-Dec>', '~'): ['epsilon'],
    ('<Cuerpo-Ritual-Dec>', '('): [')', '<Parametros-form>', '('],
    ('<Entrada>', 'Nacimiento'): ['<Instrucciones>', 'Nacimiento'],
    ('<Literales>', 'lit-oveja'): ['lit-oveja'],
    ('<Literales>', 'lit-huella'): ['lit-huella'],
    ('<Literales>', 'lit-serpiente'): ['lit-serpiente'],
    ('<Literales>', 'muerto'): ['<lit-gato>'],
    ('<Literales>', 'vivo'): ['<lit-gato>'],
    ('<Literales>', 'minimo'): ['<lit-peligro>'],
    ('<Literales>', 'bajo'): ['<lit-peligro>'],
    ('<Literales>', 'medio'): ['<lit-peligro>'],
    ('<Literales>', 'alto'): ['<lit-peligro>'],
    ('<Literales>', 'maximo'): ['<lit-peligro>'],
    ('<lit-gato>', 'muerto'): ['muerto'],
    ('<lit-gato>', 'vivo'): ['vivo'],
    ('<lit-peligro>', 'minimo'): ['minimo'],
    ('<lit-peligro>', 'bajo'): ['bajo'],
    ('<lit-peligro>', 'medio'): ['medio'],
    ('<lit-peligro>', 'alto'): ['alto'],
    ('<lit-peligro>', 'maximo'): ['maximo'],
    ('<Lit-Colmena>', '{'): ['EOF', '<Elem-conjunto>', 'lit-colm', '{'],
    ('<Elem-conjunto>', 'EOF'): ['<Elem-conjunto>', 'lit-colm', 'EOF'],
    ('<Lit-Corral>', 'EOF'): ['EOF', '<Elem-estruc>', '<Literales>', 'EOF'],
    ('<Lit-Quimera>', 'EOF'): ['EOF', '<Elem-estruc>', '<Literales>', 'EOF'],
    ('<Elem-estruc>', 'EOF'): ['epsilon'],
    ('<Atomicos>', 'EOF'): ['EOF'],
    ('<Estruc-Dec>', 'Colmena'): ['Colmena'],
    ('<Estruc-Dec>', 'Corral'): ['EOF', 'lit-oveja', 'EOF', '<Atomicos>', 'Corral'],
    ('<Estruc-Dec>', 'Quimera'): ['delfin', '<Dec-Rasgos>', '~', '<Atomicos>', 'habita', 'Id', 'plancton', 'Quimera'],
    ('<Dec-Rasgos>', 'Id'): ['<Dec-Rasgos>', '~', '<Atomicos>', 'habita', 'Id'],
    ('<Dec-Rasgos>', 'delfin'): ['epsilon'],
    ('<Identificadores>', 'Id'): ['<Ids>', 'Id'],
    ('<Ids>', 'habita'): ['epsilon'],
    ('<Ids>', 'EOF'): ['<Ids>', 'Id', 'EOF'],
    ('<Parametros-form>', 'EOF'): ['<Resto-param>', '<Atomicos>'],
    ('<Resto-param>', 'Id'): ['<Tipo-param>', '<Parametro>', 'Id'],
    ('<Resto-param>', 'EOF'): ['<Tipo-param>', '<Parametro>', 'Id', 'EOF'],
    ('<Parametro>', '~'): ['epsilon'],
    ('<Parametro>', ')'): ['epsilon'],
    ('<Parametro>', 'EOF'): ['<Resto-parametro>', 'EOF'],
    ('<Resto-parametro>', 'Id'): ['<Parametro>', 'Id'],
    ('<Resto-parametro>', 'EOF'): ['<Parametro>', 'Id', 'EOF'],
    ('<Tipo-param>', '~'): ['<Resto-tipo>', '<Atomicos>', '~'],
    ('<Tipo-param>', ')'): ['epsilon'],
    ('<Resto-tipo>', 'Id'): ['<Tipo-param>', '<Parametro>', 'Id'],
    ('<Resto-tipo>', 'EOF'): ['<Tipo-param>', '<Parametro>', 'Id', 'EOF'],
    ('<Instrucciones>', 'Id'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instrucciones>', 'Muerte'): ['epsilon'],
    ('<Instrucciones>', 'delfin'): ['epsilon'],
    ('<Instrucciones>', 'EOF'): ['<Inst-return>'],
    ('<Instruccion>', 'Id'): ['<Aux-Instruccion>', 'Id'],
    ('<Instruccion>', 'EOF'): ['~', 'EOF'],
    ('<Aux-Instruccion>', 'adopta'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Instruccion>', 'EOF'): ['~', 'Id', 'EOF'],
    ('<Control>', 'EOF'): ['<Inst-with>'],
    ('<Inst-if>', 'EOF'): ['~', '<flujos>', '<Expresion>', 'EOF'],
    ('<flujos>', 'EOF'): ['<RepeleResto>', 'EOF'],
    ('<AtraeResto>', 'Id'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeResto>', 'plancton'): ['<AtraeElse>', 'delfin', '<Instrucciones>', 'plancton'],
    ('<AtraeResto>', 'EOF'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeElse>', '~'): ['epsilon'],
    ('<AtraeElse>', 'EOF'): ['<Aux-AtraeElse>', 'EOF'],
    ('<Aux-AtraeElse>', 'Id'): ['<Instruccion>'],
    ('<Aux-AtraeElse>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-AtraeElse>', 'EOF'): ['<Instruccion>'],
    ('<RepeleResto>', 'Id'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleResto>', 'plancton'): ['<RepeleThen>', 'delfin', '<Instrucciones>', 'plancton'],
    ('<RepeleResto>', 'EOF'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleThen>', '~'): ['epsilon'],
    ('<RepeleThen>', 'EOF'): ['<Aux-RepeleThen>', 'EOF'],
    ('<Aux-RepeleThen>', 'Id'): ['<Instruccion>'],
    ('<Aux-RepeleThen>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-RepeleThen>', 'EOF'): ['<Instruccion>'],
    ('<Inst-switch>', 'EOF'): ['delfin', '<Opciones-switch>', 'plancton', '<Expresion>', 'EOF'],
    ('<Opciones-switch>', 'delfin'): ['epsilon'],
    ('<Opciones-switch>', 'EOF'): ['<Opciones-switch>', '<Instrucciones>', 'EOF'],
    ('<Inst-with>', 'EOF'): ['<Aux-with>', 'EOF', 'Id', 'EOF'],
    ('<Aux-with>', 'Id'): ['~', '<Elem-cuerpo-with>'],
    ('<Aux-with>', '~'): ['~', '<Elem-cuerpo-with>'],
    ('<Aux-with>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Elem-cuerpo-with>', 'Id'): ['<Elem-cuerpo-with>', '~', '<Literales>', 'adopta', 'Id'],
    ('<Elem-cuerpo-with>', '~'): ['epsilon'],
    ('<Ciclos>', 'EOF'): ['<Inst-for>'],
    ('<Inst-while>', 'EOF'): ['<Aux-while>', 'EOF', '<Comparacion>', 'EOF'],
    ('<Aux-while>', 'Id'): ['~', '<Instruccion>'],
    ('<Aux-while>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-while>', 'EOF'): ['~', '<Instruccion>'],
    ('<Inst-repeat>', 'EOF'): ['~', '<Comparacion>', 'EOF', '<Instrucciones>', 'EOF'],
    ('<Inst-for>', 'EOF'): ['<Aux-for>', 'EOF', 'lit-oveja', 'EOF', 'lit-oveja', 'EOF', 'lit-oveja', 'EOF', '<Inic-expr>', 'EOF'],
    ('<Aux-for>', 'Id'): ['~', '<Instruccion>'],
    ('<Aux-for>', 'plancton'): ['~', 'delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-for>', 'EOF'): ['~', '<Instruccion>'],
    ('<Inic-expr>', 'Id'): ['<Aux-Inic-expr>', 'Id'],
    ('<Aux-Inic-expr>', 'adopta'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Inic-expr>', 'EOF'): ['~', 'Id', 'EOF'],
    ('<Inst-return>', 'EOF'): ['~', '<Expresion>', 'EOF'],
    ('<Resto-Asignacion-Id>', 'adopta'): ['<Resto-Adopta>', 'adopta'],
    ('<Resto-Asignacion-Id>', 'EOF'): ['~', '<Literales>', 'adopta', 'EOF', 'EOF'],
    ('<Resto-Adopta>', '('): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lit-oveja'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lit-huella'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lit-serpiente'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'muerto'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'vivo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'minimo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'bajo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'medio'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'alto'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'maximo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', '{'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'EOF'): ['~', '<Expresion>'],
    ('<Op-asignacion>', 'EOF'): ['EOF'],
    ('<Expresion>', '('): ['<Operaciones>'],
    ('<Expresion>', 'lit-oveja'): ['<Operaciones>'],
    ('<Expresion>', 'lit-huella'): ['<Operaciones>'],
    ('<Expresion>', 'lit-serpiente'): ['<Operaciones>'],
    ('<Expresion>', 'muerto'): ['<Operaciones>'],
    ('<Expresion>', 'vivo'): ['<Operaciones>'],
    ('<Expresion>', 'minimo'): ['<Operaciones>'],
    ('<Expresion>', 'bajo'): ['<Operaciones>'],
    ('<Expresion>', 'medio'): ['<Operaciones>'],
    ('<Expresion>', 'alto'): ['<Operaciones>'],
    ('<Expresion>', 'maximo'): ['<Operaciones>'],
    ('<Expresion>', '{'): ['<Operaciones>'],
    ('<Expresion>', 'EOF'): ['<Operaciones>'],
    ('<Operaciones>', '('): ['<Aux-Operaciones-1>', '('],
    ('<Operaciones>', 'lit-oveja'): ['<Aux-Operaciones-2>', 'lit-oveja'],
    ('<Operaciones>', 'lit-huella'): ['<Comparacion>'],
    ('<Operaciones>', 'lit-serpiente'): ['<Aux-Operaciones-4>', 'lit-serpiente'],
    ('<Operaciones>', 'muerto'): ['<Aux-Operaciones-3>', '<lit-gato>'],
    ('<Operaciones>', 'vivo'): ['<Aux-Operaciones-3>', '<lit-gato>'],
    ('<Operaciones>', 'minimo'): ['<Aux-Operaciones-5>', '<lit-peligro>'],
    ('<Operaciones>', 'bajo'): ['<Aux-Operaciones-5>', '<lit-peligro>'],
    ('<Operaciones>', 'medio'): ['<Aux-Operaciones-5>', '<lit-peligro>'],
    ('<Operaciones>', 'alto'): ['<Aux-Operaciones-5>', '<lit-peligro>'],
    ('<Operaciones>', 'maximo'): ['<Aux-Operaciones-5>', '<lit-peligro>'],
    ('<Operaciones>', '{'): ['<Conjuntos>'],
    ('<Operaciones>', 'EOF'): ['<Creativas>'],
    ('<Aux-Operaciones-1>', '('): [')', '<Aritmeticas-2>'],
    ('<Aux-Operaciones-1>', 'lit-oveja'): [')', '<Aritmeticas-2>'],
    ('<Aux-Operaciones-1>', 'lit-huella'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', 'lit-serpiente'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', 'muerto'): [')', '<Aux-Operando-log>'],
    ('<Aux-Operaciones-1>', 'vivo'): [')', '<Aux-Operando-log>'],
    ('<Aux-Operaciones-1>', 'minimo'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', 'bajo'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', 'medio'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', 'alto'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', 'maximo'): [')', '<Aux-Operando-com>'],
    ('<Aux-Operaciones-1>', '{'): ['<Operando-creat>', '<Aux-Op-creativa>', ')', '<Expresion>'],
    ('<Aux-Operaciones-1>', 'EOF'): ['<Operando-creat>', '<Aux-Op-creativa>', ')', '<Expresion>'],
    ('<Aux-Operaciones-2>', 'EOF'): ['<Operando-com>', '<Op-com>'],
    ('<Aux-Operaciones-3>', 'EOF'): ['<Operando-com>', '<Op-com>'],
    ('<Aux-Operaciones-4>', 'EOF'): ['<Operando-com>', '<Op-com>'],
    ('<Aux-Operaciones-5>', 'EOF'): ['<Operando-com>', '<Op-com>'],
    ('<Llamada-func>', 'EOF'): ['~', ')', '<Parametros-real>', '(', 'EOF'],
    ('<Parametros-real>', 'lit-oveja'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'lit-huella'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'lit-serpiente'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'muerto'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'vivo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'minimo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'bajo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'medio'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'alto'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'maximo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametro-real>', ')'): ['epsilon'],
    ('<Parametro-real>', 'EOF'): ['<Parametro-real>', '<Literales>', 'EOF'],
    ('<Aritmeticas>', 'EOF'): ['<Aux-Arit>', 'EOF'],
    ('<Aritmeticas-2>', '('): ['<Aux-Arit>', '<Operando-arit>'],
    ('<Aritmeticas-2>', 'lit-oveja'): ['<Aux-Arit>', '<Operando-arit>'],
    ('<Aritmeticas-2>', 'EOF'): ['<Aux-Arit>', '<Operando-arit>'],
    ('<Aux-Arit>', 'EOF'): ['<lit-peligro>', 'EOF'],
    ('<Operando-arit>', '('): [')', '<Aritmeticas-2>', '('],
    ('<Operando-arit>', 'lit-oveja'): ['lit-oveja'],
    ('<Operando-arit>', 'EOF'): ['EOF'],
    ('<Caracteres>', 'EOF'): ['<Operando-car>', 'EOF'],
    ('<Operando-car>', 'lit-huella'): ['lit-huella'],
    ('<Operando-car>', 'EOF'): ['EOF'],
    ('<Logicas>', 'EOF'): ['<Operando-log>', '<Op-Log>', 'EOF'],
    ('<Logicas-2>', '('): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Logicas-2>', 'muerto'): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Logicas-2>', 'vivo'): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Logicas-2>', 'EOF'): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Operando-log>', '('): [')', '<Aux-Operando-log>', '('],
    ('<Operando-log>', 'muerto'): ['<lit-gato>'],
    ('<Operando-log>', 'vivo'): ['<lit-gato>'],
    ('<Operando-log>', 'EOF'): ['EOF'],
    ('<Aux-Operando-log>', '('): ['<Logicas-2>'],
    ('<Aux-Operando-log>', 'muerto'): ['<Logicas-2>'],
    ('<Aux-Operando-log>', 'vivo'): ['<Logicas-2>'],
    ('<Aux-Operando-log>', 'EOF'): ['<Logicas-2>'],
    ('<Op-Log>', 'EOF'): ['EOF'],
    ('<Strings>', 'EOF'): ['<Aux-Strings-1>', '<Operando-str>'],
    ('<Aux-Strings-1>', 'EOF'): ['<Operando-str>', 'EOF'],
    ('<Operando-str>', 'EOF'): ['EOF'],
    ('<Conjuntos>', '{'): ['<Operando-conj>', '<Op-conj>', '<Operando-conj>'],
    ('<Conjuntos>', 'EOF'): ['<Operando-conj>', '<Op-conj>', '<Operando-conj>'],
    ('<Op-conj>', 'EOF'): ['EOF'],
    ('<Operando-conj>', '{'): ['<Lit-Colmena>'],
    ('<Operando-conj>', 'EOF'): ['EOF'],
    ('<Comparacion>', 'lit-huella'): ['<Operando-com>', '<Op-com>', 'lit-huella'],
    ('<Comparacion>', 'EOF'): ['<Operando-com>', '<Op-com>', 'EOF'],
    ('<Comparacion-2>', '('): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'lit-oveja'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'lit-huella'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'lit-serpiente'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'muerto'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'vivo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'minimo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'bajo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'medio'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'alto'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'maximo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'EOF'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Operando-com>', '('): [')', '<Aux-Operando-com>', '('],
    ('<Operando-com>', 'lit-oveja'): ['<Literales>'],
    ('<Operando-com>', 'lit-huella'): ['<Literales>'],
    ('<Operando-com>', 'lit-serpiente'): ['<Literales>'],
    ('<Operando-com>', 'muerto'): ['<Literales>'],
    ('<Operando-com>', 'vivo'): ['<Literales>'],
    ('<Operando-com>', 'minimo'): ['<Literales>'],
    ('<Operando-com>', 'bajo'): ['<Literales>'],
    ('<Operando-com>', 'medio'): ['<Literales>'],
    ('<Operando-com>', 'alto'): ['<Literales>'],
    ('<Operando-com>', 'maximo'): ['<Literales>'],
    ('<Operando-com>', 'EOF'): ['EOF'],
    ('<Aux-Operando-com>', '('): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'lit-oveja'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'lit-huella'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'lit-serpiente'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'muerto'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'vivo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'minimo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'bajo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'medio'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'alto'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'maximo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'EOF'): ['<Comparacion-2>'],
    ('<Op-com>', 'EOF'): ['EOF'],
    ('<Creativas>', 'EOF'): ['<Op-creativa>'],
    ('<Op-creativa>', 'EOF'): ['<Operando-creat>', '<Aux-Op-creativa>', 'EOF'],
    ('<Aux-Op-creativa>', 'EOF'): ['EOF'],
    ('<Operando-creat>', 'minimo'): ['<lit-peligro>'],
    ('<Operando-creat>', 'bajo'): ['<lit-peligro>'],
    ('<Operando-creat>', 'medio'): ['<lit-peligro>'],
    ('<Operando-creat>', 'alto'): ['<lit-peligro>'],
    ('<Operando-creat>', 'maximo'): ['<lit-peligro>'],
    ('<Operando-creat>', 'EOF'): ['EOF'],
    ('<Control-creativo>', 'EOF'): ['delfin', '<Instrucciones>', 'plancton', 'EOF', 'EOF'],
}
