# Archivo generado automaticamente desde Gramatica.c
TABLA_PARSING = {
    ('<Titulo>', 'Reino'): [233, '~~', 'Id', 232, 'Muerte', '<Entrada>', '<Procesos>', '<Variables>', '<Tipos>', '<Constantes>', '~', 'Id', 'Reino', 231],
    ('<Constantes>', 'Reserva'): ['~~', '<Def-constante>', '~', '<Literales>', 'fosil', 'Id', 234, 'Reserva'],
    ('<Constantes>', 'Especies'): ['epsilon'],
    ('<Constantes>', 'Organismos'): ['epsilon'],
    ('<Constantes>', 'Huevos'): ['epsilon'],
    ('<Constantes>', 'Comportamientos'): ['epsilon'],
    ('<Def-constante>', 'Id'): ['<Def-constante>', '~', '<Literales>', 'fosil', 'Id', 234],
    ('<Def-constante>', '~~'): ['epsilon'],
    ('<Tipos>', 'Especies'): ['~~', '<Def-tipo>', '~', '<Tipos-dec>', 'cripsis', 'Id', 234, 'Especies'],
    ('<Tipos>', 'Organismos'): ['epsilon'],
    ('<Tipos>', 'Huevos'): ['epsilon'],
    ('<Tipos>', 'Comportamientos'): ['epsilon'],
    ('<Def-tipo>', 'Id'): ['<Def-tipo>', '~', '<Tipos-dec>', 'cripsis', 'Id', 234],
    ('<Def-tipo>', '~~'): ['epsilon'],
    ('<Tipos-dec>', 'Id_tipo_declarado'): ['Id_tipo_declarado', 235],
    ('<Tipos-dec>', 'Colmena'): ['<Estruc-Dec>'],
    ('<Tipos-dec>', 'Corral'): ['<Estruc-Dec>'],
    ('<Tipos-dec>', 'Quimera'): ['<Estruc-Dec>'],
    ('<Tipos-dec>', 'Oveja'): ['<Atomicos>'],
    ('<Tipos-dec>', 'Huella'): ['<Atomicos>'],
    ('<Tipos-dec>', 'Gato'): ['<Atomicos>'],
    ('<Tipos-dec>', 'peligro'): ['<Atomicos>'],
    ('<Tipos-dec>', 'Serpiente'): ['<Atomicos>'],
    ('<Variables>', 'Organismos'): ['~~', '<Dec-variable>', '~', '<Var-Cont>', 'Organismos'],
    ('<Variables>', 'Huevos'): ['epsilon'],
    ('<Variables>', 'Comportamientos'): ['epsilon'],
    ('<Var-Cont>', 'Id'): ['<Aux-Var-Cont>', '<Tipo-Habita>', 'habita', '<Identificadores>'],
    ('<Aux-Var-Cont>', '~'): ['epsilon'],
    ('<Aux-Var-Cont>', 'adopta'): ['<Literal-Adopta>', 236, 'adopta'],
    ('<Tipo-Habita>', 'Colmena'): ['Colmena'],
    ('<Tipo-Habita>', 'Corral'): ['Corral'],
    ('<Tipo-Habita>', 'Quimera'): ['Quimera'],
    ('<Tipo-Habita>', 'Oveja'): ['<Atomicos>'],
    ('<Tipo-Habita>', 'Huella'): ['<Atomicos>'],
    ('<Tipo-Habita>', 'Gato'): ['<Atomicos>'],
    ('<Tipo-Habita>', 'peligro'): ['<Atomicos>'],
    ('<Tipo-Habita>', 'Serpiente'): ['<Atomicos>'],
    ('<Literal-Adopta>', 'lit-oveja'): ['<Literales>'],
    ('<Literal-Adopta>', 'lit-huella'): ['<Literales>'],
    ('<Literal-Adopta>', 'lit-serpiente'): ['<Literales>'],
    ('<Literal-Adopta>', 'muerto'): ['<Literales>'],
    ('<Literal-Adopta>', 'vivo'): ['<Literales>'],
    ('<Literal-Adopta>', 'minimo'): ['<Literales>'],
    ('<Literal-Adopta>', 'bajo'): ['<Literales>'],
    ('<Literal-Adopta>', 'medio'): ['<Literales>'],
    ('<Literal-Adopta>', 'alto'): ['<Literales>'],
    ('<Literal-Adopta>', 'maximo'): ['<Literales>'],
    ('<Literal-Adopta>', '{'): ['<Lit-Colmena>'],
    ('<Literal-Adopta>', '{['): ['<Lit-Corral>'],
    ('<Literal-Adopta>', '{@'): ['<Lit-Quimera>'],
    ('<Dec-variable>', 'Id'): ['<Dec-variable>', '~', '<Resto-Dec>'],
    ('<Dec-variable>', '~~'): ['epsilon'],
    ('<Resto-Dec>', 'Id'): ['<Aux-Resto-Dec>', '<Lugar>', 'habita', '<Identificadores>'],
    ('<Aux-Resto-Dec>', '~'): ['epsilon'],
    ('<Aux-Resto-Dec>', 'adopta'): ['<Literal-Tipo>', 236, 'adopta'],
    ('<Lugar>', 'Colmena'): ['Colmena'],
    ('<Lugar>', 'Corral'): ['Corral'],
    ('<Lugar>', 'Quimera'): ['Quimera'],
    ('<Lugar>', 'Oveja'): ['<Atomicos>'],
    ('<Lugar>', 'Huella'): ['<Atomicos>'],
    ('<Lugar>', 'Gato'): ['<Atomicos>'],
    ('<Lugar>', 'peligro'): ['<Atomicos>'],
    ('<Lugar>', 'Serpiente'): ['<Atomicos>'],
    ('<Literal-Tipo>', 'lit-oveja'): ['<Literales>'],
    ('<Literal-Tipo>', 'lit-huella'): ['<Literales>'],
    ('<Literal-Tipo>', 'lit-serpiente'): ['<Literales>'],
    ('<Literal-Tipo>', 'muerto'): ['<Literales>'],
    ('<Literal-Tipo>', 'vivo'): ['<Literales>'],
    ('<Literal-Tipo>', 'minimo'): ['<Literales>'],
    ('<Literal-Tipo>', 'bajo'): ['<Literales>'],
    ('<Literal-Tipo>', 'medio'): ['<Literales>'],
    ('<Literal-Tipo>', 'alto'): ['<Literales>'],
    ('<Literal-Tipo>', 'maximo'): ['<Literales>'],
    ('<Literal-Tipo>', '{'): ['<Lit-Colmena>'],
    ('<Literal-Tipo>', '{['): ['<Lit-Corral>'],
    ('<Literal-Tipo>', '{@'): ['<Lit-Quimera>'],
    ('<Procesos>', 'Huevos'): ['<Con-Rutinas>', '<Prototipos>'],
    ('<Procesos>', 'Comportamientos'): ['<Con-Rutinas>', '<Prototipos>'],
    ('<Con-Rutinas>', 'Comportamientos'): ['<Rutinas>'],
    ('<Con-Rutinas>', 'Nacimiento'): ['<Rutinas>'],
    ('<Prototipos>', 'Huevos'): ['~~', '<Aux-Prototipos>', 'Huevos'],
    ('<Prototipos>', 'Comportamientos'): ['epsilon'],
    ('<Aux-Prototipos>', 'entrenar'): ['<Dec-encabezados>', '~', '<Atomicos>', ')', '<Parametros-form>', '(', 'Id', 234, 'entrenar'],
    ('<Aux-Prototipos>', 'ritual'): ['<Dec-encabezados>', '~', ')', '<Parametros-form>', '(', 'Id', 234, 'ritual'],
    ('<Dec-encabezados>', '~~'): ['epsilon'],
    ('<Dec-encabezados>', 'entrenar'): ['<Dec-encabezados>', '~', '<Atomicos>', ')', '<Parametros-form>', '(', 'Id', 234, 'entrenar'],
    ('<Dec-encabezados>', 'ritual'): ['<Dec-encabezados>', '~', ')', '<Parametros-form>', '(', 'Id', 234, 'ritual'],
    ('<Rutinas>', 'Comportamientos'): ['~~', '<Aux-Rutinas>', 'Comportamientos'],
    ('<Rutinas>', 'Nacimiento'): ['epsilon'],
    ('<Aux-Rutinas>', 'entrenar'): ['<Dec-rutinas>', 'delfin', 238, '<Instrucciones>', 'plancton', '~', '<Cuerpo-Entrenar>', 237, 'Id', 234, 'entrenar'],
    ('<Aux-Rutinas>', 'ritual'): ['<Dec-rutinas>', 'delfin', 238, '<Instrucciones>', 'plancton', '~', '<Cuerpo-Ritual>', 237, 'Id', 234, 'ritual'],
    ('<Cuerpo-Entrenar>', '~'): ['epsilon'],
    ('<Cuerpo-Entrenar>', '('): ['<Atomicos>', ')', '<Parametros-form>', '('],
    ('<Cuerpo-Ritual>', '~'): ['epsilon'],
    ('<Cuerpo-Ritual>', '('): [')', '<Parametros-form>', '('],
    ('<Dec-rutinas>', '~~'): ['epsilon'],
    ('<Dec-rutinas>', 'entrenar'): ['<Dec-rutinas>', 'delfin', 238, '<Instrucciones>', 'plancton', '~', '<Cuerpo-Entrenar-Dec>', 237, 'Id', 234, 'entrenar'],
    ('<Dec-rutinas>', 'ritual'): ['<Dec-rutinas>', 'delfin', 238, '<Instrucciones>', 'plancton', '~', '<Cuerpo-Ritual-Dec>', 237, 'Id', 234, 'ritual'],
    ('<Cuerpo-Entrenar-Dec>', '~'): ['epsilon'],
    ('<Cuerpo-Entrenar-Dec>', '('): ['<Atomicos>', ')', '<Parametros-form>', '('],
    ('<Cuerpo-Ritual-Dec>', '~'): ['epsilon'],
    ('<Cuerpo-Ritual-Dec>', '('): [')', '<Parametros-form>', '('],
    ('<Entrada>', 'Nacimiento'): ['<Instrucciones>', 'Nacimiento'],
    ('<Literales>', 'lit-oveja'): ['lit-oveja'],
    ('<Literales>', 'lit-huella'): ['lit-huella'],
    ('<Literales>', 'lit-serpiente'): ['lit-serpiente'],
    ('<Literales>', 'muerto'): ['<lit-gato>'],
    ('<Literales>', 'vivo'): ['<lit-gato>'],
    ('<Literales>', 'minimo'): ['<lit-peligro>'],
    ('<Literales>', 'bajo'): ['<lit-peligro>'],
    ('<Literales>', 'medio'): ['<lit-peligro>'],
    ('<Literales>', 'alto'): ['<lit-peligro>'],
    ('<Literales>', 'maximo'): ['<lit-peligro>'],
    ('<lit-gato>', 'muerto'): ['muerto'],
    ('<lit-gato>', 'vivo'): ['vivo'],
    ('<lit-peligro>', 'minimo'): ['minimo'],
    ('<lit-peligro>', 'bajo'): ['bajo'],
    ('<lit-peligro>', 'medio'): ['medio'],
    ('<lit-peligro>', 'alto'): ['alto'],
    ('<lit-peligro>', 'maximo'): ['maximo'],
    ('<Lit-Colmena>', '{'): ['}', '<Elem-conjunto>', 'lit-colm', '{'],
    ('<Elem-conjunto>', '}'): ['epsilon'],
    ('<Elem-conjunto>', ','): ['<Elem-conjunto>', 'lit-colm', ','],
    ('<Lit-Corral>', '{['): [']}', '<Elem-estruc>', '<Literales>', '{['],
    ('<Lit-Quimera>', '{@'): ['@}', '<Elem-estruc>', '<Literales>', '{@'],
    ('<Elem-estruc>', ','): ['<Elem-estruc>', '<Literales>', ','],
    ('<Elem-estruc>', ']}'): ['epsilon'],
    ('<Elem-estruc>', '@}'): ['epsilon'],
    ('<Atomicos>', 'Oveja'): ['Oveja'],
    ('<Atomicos>', 'Huella'): ['Huella'],
    ('<Atomicos>', 'Gato'): ['Gato'],
    ('<Atomicos>', 'peligro'): ['peligro'],
    ('<Atomicos>', 'Serpiente'): ['Serpiente'],
    ('<Estruc-Dec>', 'Colmena'): ['Colmena'],
    ('<Estruc-Dec>', 'Corral'): [']', 'lit-oveja', '[', '<Atomicos>', 'Corral'],
    ('<Estruc-Dec>', 'Quimera'): ['delfin', '<Dec-Rasgos>', '~', '<Atomicos>', 'habita', 'Id', 234, 'plancton', 'Quimera'],
    ('<Dec-Rasgos>', 'Id'): ['<Dec-Rasgos>', '~', '<Atomicos>', 'habita', 'Id', 234],
    ('<Dec-Rasgos>', 'delfin'): ['epsilon'],
    ('<Identificadores>', 'Id'): ['<Ids>', 'Id', 234],
    ('<Ids>', 'habita'): ['epsilon'],
    ('<Ids>', ','): ['<Ids>', 'Id', 234, ','],
    ('<Parametros-form>', 'Oveja'): ['<Resto-param>', '<Atomicos>'],
    ('<Parametros-form>', 'Huella'): ['<Resto-param>', '<Atomicos>'],
    ('<Parametros-form>', 'Gato'): ['<Resto-param>', '<Atomicos>'],
    ('<Parametros-form>', 'peligro'): ['<Resto-param>', '<Atomicos>'],
    ('<Parametros-form>', 'Serpiente'): ['<Resto-param>', '<Atomicos>'],
    ('<Resto-param>', 'Id'): ['<Tipo-param>', '<Parametro>', 'Id', 239],
    ('<Resto-param>', '><>'): ['<Tipo-param>', '<Parametro>', 'Id', 239, '><>'],
    ('<Parametro>', '~'): ['epsilon'],
    ('<Parametro>', ')'): ['epsilon'],
    ('<Parametro>', ','): ['<Resto-parametro>', ','],
    ('<Resto-parametro>', 'Id'): ['<Parametro>', 'Id', 239],
    ('<Resto-parametro>', '><>'): ['<Parametro>', 'Id', 239, '><>'],
    ('<Tipo-param>', '~'): ['<Resto-tipo>', '<Atomicos>', '~'],
    ('<Tipo-param>', ')'): ['epsilon'],
    ('<Resto-tipo>', 'Id'): ['<Tipo-param>', '<Parametro>', 'Id', 239],
    ('<Resto-tipo>', '><>'): ['<Tipo-param>', '<Parametro>', 'Id', 239, '><>'],
    ('<Instrucciones>', 'Id'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instrucciones>', 'Muerte'): ['epsilon'],
    ('<Instrucciones>', 'delfin'): ['epsilon'],
    ('<Instrucciones>', 'dodo'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instrucciones>', 'liebre'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instrucciones>', 'tortuga'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instrucciones>', 'cortejo'): ['<Instrucciones>', '<Control>'],
    ('<Instrucciones>', 'pulpo'): ['<Instrucciones>', '<Control>'],
    ('<Instrucciones>', 'tentaculo'): ['epsilon'],
    ('<Instrucciones>', 'cabeza'): ['epsilon'],
    ('<Instrucciones>', 'canguro'): ['<Instrucciones>', '<Control>'],
    ('<Instrucciones>', 'tiburon'): ['<Instrucciones>', '<Ciclos>'],
    ('<Instrucciones>', 'loro'): ['<Instrucciones>', '<Ciclos>'],
    ('<Instrucciones>', 'mudo'): ['epsilon'],
    ('<Instrucciones>', 'migrar'): ['<Instrucciones>', '<Ciclos>'],
    ('<Instrucciones>', 'Perro'): ['<Inst-return>'],
    ('<Instrucciones>', 'OSO'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instrucciones>', 'PANDA'): ['<Instrucciones>', '<Instruccion>'],
    ('<Instruccion>', 'Id'): ['<Aux-Instruccion>', 'Id', 240],
    ('<Instruccion>', 'dodo'): ['~', 'dodo'],
    ('<Instruccion>', 'liebre'): ['~', 'liebre'],
    ('<Instruccion>', 'tortuga'): ['~', 'tortuga'],
    ('<Instruccion>', 'OSO'): ['delfin', '<Instrucciones>', 'plancton', 'come', '<Comparacion>', 'OSO'],
    ('<Instruccion>', 'PANDA'): ['delfin', '<Instrucciones>', 'plancton', 'come', 'PANDA'],
    ('<Aux-Instruccion>', 'adopta'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Instruccion>', '['): ['<Resto-Asignacion-Id>'],
    ('<Aux-Instruccion>', 'Camaleon'): ['~', '<Atomicos>', 'Camaleon'],
    ('<Aux-Instruccion>', '$'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Instruccion>', '@'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Instruccion>', 'Acariciar'): ['~', 'Id', 240, 'Acariciar'],
    ('<Aux-Instruccion>', 'Reprender'): ['~', 'Id', 240, 'Reprender'],
    ('<Control>', 'cortejo'): ['<Inst-if>'],
    ('<Control>', 'pulpo'): ['<Inst-switch>'],
    ('<Control>', 'canguro'): ['<Inst-with>'],
    ('<Inst-if>', 'cortejo'): ['~', '<flujos>', '<Expresion>', 241, 'cortejo'],
    ('<flujos>', 'atrae'): ['<AtraeResto>', 'atrae'],
    ('<flujos>', 'repele'): ['<RepeleResto>', 'repele'],
    ('<AtraeResto>', 'Id'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeResto>', 'plancton'): ['<AtraeElse>', 'delfin', '<Instrucciones>', 'plancton'],
    ('<AtraeResto>', 'dodo'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeResto>', 'liebre'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeResto>', 'tortuga'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeResto>', 'OSO'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeResto>', 'PANDA'): ['<AtraeElse>', '<Instruccion>'],
    ('<AtraeElse>', '~'): ['epsilon'],
    ('<AtraeElse>', 'repele'): ['<Aux-AtraeElse>', 'repele'],
    ('<Aux-AtraeElse>', 'Id'): ['<Instruccion>'],
    ('<Aux-AtraeElse>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-AtraeElse>', 'dodo'): ['<Instruccion>'],
    ('<Aux-AtraeElse>', 'liebre'): ['<Instruccion>'],
    ('<Aux-AtraeElse>', 'tortuga'): ['<Instruccion>'],
    ('<Aux-AtraeElse>', 'OSO'): ['<Instruccion>'],
    ('<Aux-AtraeElse>', 'PANDA'): ['<Instruccion>'],
    ('<RepeleResto>', 'Id'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleResto>', 'plancton'): ['<RepeleThen>', 'delfin', '<Instrucciones>', 'plancton'],
    ('<RepeleResto>', 'dodo'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleResto>', 'liebre'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleResto>', 'tortuga'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleResto>', 'OSO'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleResto>', 'PANDA'): ['<RepeleThen>', '<Instruccion>'],
    ('<RepeleThen>', '~'): ['epsilon'],
    ('<RepeleThen>', 'atrae'): ['<Aux-RepeleThen>', 'atrae'],
    ('<Aux-RepeleThen>', 'Id'): ['<Instruccion>'],
    ('<Aux-RepeleThen>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-RepeleThen>', 'dodo'): ['<Instruccion>'],
    ('<Aux-RepeleThen>', 'liebre'): ['<Instruccion>'],
    ('<Aux-RepeleThen>', 'tortuga'): ['<Instruccion>'],
    ('<Aux-RepeleThen>', 'OSO'): ['<Instruccion>'],
    ('<Aux-RepeleThen>', 'PANDA'): ['<Instruccion>'],
    ('<Inst-switch>', 'pulpo'): ['delfin', '<Opciones-switch>', 'plancton', '<Expresion>', 'pulpo'],
    ('<Opciones-switch>', 'delfin'): ['epsilon'],
    ('<Opciones-switch>', 'tentaculo'): ['<Opciones-switch>', '<Instrucciones>', ':', '<Literales>', 'tentaculo'],
    ('<Opciones-switch>', 'cabeza'): ['<Opciones-switch>', '<Instrucciones>', 'cabeza', 242],
    ('<Inst-with>', 'canguro'): ['<Aux-with>', 'Bolsa', 'Id', 'canguro'],
    ('<Aux-with>', 'Id'): ['~', '<Elem-cuerpo-with>'],
    ('<Aux-with>', '~'): ['~', '<Elem-cuerpo-with>'],
    ('<Aux-with>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Elem-cuerpo-with>', 'Id'): ['<Elem-cuerpo-with>', '~', '<Literales>', 243, 'adopta', 'Id', 240],
    ('<Elem-cuerpo-with>', '~'): ['epsilon'],
    ('<Ciclos>', 'tiburon'): ['<Inst-while>'],
    ('<Ciclos>', 'loro'): ['<Inst-repeat>'],
    ('<Ciclos>', 'migrar'): ['<Inst-for>'],
    ('<Inst-while>', 'tiburon'): ['<Aux-while>', 'sangre', '<Comparacion>', 244, 'tiburon'],
    ('<Aux-while>', 'Id'): ['~', '<Instruccion>'],
    ('<Aux-while>', 'plancton'): ['delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-while>', 'dodo'): ['~', '<Instruccion>'],
    ('<Aux-while>', 'liebre'): ['~', '<Instruccion>'],
    ('<Aux-while>', 'tortuga'): ['~', '<Instruccion>'],
    ('<Aux-while>', 'OSO'): ['~', '<Instruccion>'],
    ('<Aux-while>', 'PANDA'): ['~', '<Instruccion>'],
    ('<Inst-repeat>', 'loro'): ['~', '<Comparacion>', 245, 'mudo', '<Instrucciones>', 'loro'],
    ('<Inst-for>', 'migrar'): ['<Aux-for>', 'ruta', 'lit-oveja', 'paso', 'lit-oveja', 'hasta', 'lit-oveja', 'desde', '<Inic-expr>', 'migrar'],
    ('<Aux-for>', 'Id'): ['~', '<Instruccion>'],
    ('<Aux-for>', 'plancton'): ['~', 'delfin', '<Instrucciones>', 'plancton'],
    ('<Aux-for>', 'dodo'): ['~', '<Instruccion>'],
    ('<Aux-for>', 'liebre'): ['~', '<Instruccion>'],
    ('<Aux-for>', 'tortuga'): ['~', '<Instruccion>'],
    ('<Aux-for>', 'OSO'): ['~', '<Instruccion>'],
    ('<Aux-for>', 'PANDA'): ['~', '<Instruccion>'],
    ('<Inic-expr>', 'Id'): ['<Aux-Inic-expr>', 'Id', 240],
    ('<Aux-Inic-expr>', 'adopta'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Inic-expr>', '['): ['<Resto-Asignacion-Id>'],
    ('<Aux-Inic-expr>', 'desde'): ['epsilon'],
    ('<Aux-Inic-expr>', '$'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Inic-expr>', '@'): ['<Resto-Asignacion-Id>'],
    ('<Aux-Inic-expr>', 'Acariciar'): ['~', 'Id', 246, 240, 'Acariciar'],
    ('<Aux-Inic-expr>', 'Reprender'): ['~', 'Id', 246, 240, 'Reprender'],
    ('<Inst-return>', 'Perro'): ['~', '<Expresion>', 248, 'Perro', 247],
    ('<Resto-Asignacion-Id>', 'adopta'): ['<Resto-Adopta>', 'adopta'],
    ('<Resto-Asignacion-Id>', '['): ['~', '<Lit-Corral>', 'adopta', ']', 'lit-oveja', '['],
    ('<Resto-Asignacion-Id>', '$'): ['~', '<Literales>', 'adopta', 'lit-oveja', '$'],
    ('<Resto-Asignacion-Id>', '@'): ['~', '<Literales>', 'adopta', 'Id-atributo', '@'],
    ('<Resto-Adopta>', '('): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lit-oveja'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lit-huella'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lit-serpiente'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'muerto'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'vivo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'minimo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'bajo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'medio'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'alto'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'maximo'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', '{'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'boa'): ['~', '<Expresion>', '<Op-asignacion>'],
    ('<Resto-Adopta>', 'can'): ['~', '<Expresion>', '<Op-asignacion>'],
    ('<Resto-Adopta>', 'emu'): ['~', '<Expresion>', '<Op-asignacion>'],
    ('<Resto-Adopta>', 'gnu'): ['~', '<Expresion>', '<Op-asignacion>'],
    ('<Resto-Adopta>', 'yak'): ['~', '<Expresion>', '<Op-asignacion>'],
    ('<Resto-Adopta>', 'conejo?'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'lobo?'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Salvaje'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Docil'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'escamas'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'acechar'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'desolado?'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'calmar'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'amenaza'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Func'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Op_Aritmetico'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Op_Logico'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Op_Str'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Op_Conj'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Op_Com'): ['~', '<Expresion>'],
    ('<Resto-Adopta>', 'Id_Op_Creat'): ['~', '<Expresion>'],
    ('<Op-asignacion>', 'boa'): ['boa'],
    ('<Op-asignacion>', 'can'): ['can'],
    ('<Op-asignacion>', 'emu'): ['emu'],
    ('<Op-asignacion>', 'gnu'): ['gnu'],
    ('<Op-asignacion>', 'yak'): ['yak'],
    ('<Expresion>', '('): ['<Operaciones>'],
    ('<Expresion>', 'lit-oveja'): ['<Operaciones>'],
    ('<Expresion>', 'lit-huella'): ['<Operaciones>'],
    ('<Expresion>', 'lit-serpiente'): ['<Operaciones>'],
    ('<Expresion>', 'muerto'): ['<Operaciones>'],
    ('<Expresion>', 'vivo'): ['<Operaciones>'],
    ('<Expresion>', 'minimo'): ['<Operaciones>'],
    ('<Expresion>', 'bajo'): ['<Operaciones>'],
    ('<Expresion>', 'medio'): ['<Operaciones>'],
    ('<Expresion>', 'alto'): ['<Operaciones>'],
    ('<Expresion>', 'maximo'): ['<Operaciones>'],
    ('<Expresion>', '{'): ['<Operaciones>'],
    ('<Expresion>', 'conejo?'): ['<Operaciones>'],
    ('<Expresion>', 'lobo?'): ['<Operaciones>'],
    ('<Expresion>', 'Salvaje'): ['<Operaciones>'],
    ('<Expresion>', 'Docil'): ['<Operaciones>'],
    ('<Expresion>', 'escamas'): ['<Operaciones>'],
    ('<Expresion>', 'acechar'): ['<Operaciones>'],
    ('<Expresion>', 'desolado?'): ['<Operaciones>'],
    ('<Expresion>', 'calmar'): ['<Operaciones>'],
    ('<Expresion>', 'amenaza'): ['<Operaciones>'],
    ('<Expresion>', 'Id_Func'): ['<Llamada-func>'],
    ('<Expresion>', 'Id_Op_Aritmetico'): ['<Operaciones>'],
    ('<Expresion>', 'Id_Op_Logico'): ['<Operaciones>'],
    ('<Expresion>', 'Id_Op_Str'): ['<Operaciones>'],
    ('<Expresion>', 'Id_Op_Conj'): ['<Operaciones>'],
    ('<Expresion>', 'Id_Op_Com'): ['<Operaciones>'],
    ('<Expresion>', 'Id_Op_Creat'): ['<Operaciones>'],
    ('<Operaciones>', '('): ['<Arit_Log>', ')', '<Inicio_parent_Aux>', '('],
    ('<Operaciones>', 'lit-oveja'): ['<Aux-Arit>', 'lit-oveja'],
    ('<Operaciones>', 'lit-huella'): ['<Comparacion>'],
    ('<Operaciones>', 'lit-serpiente'): ['<Aux-Strings-1>', '<Operando-str>'],
    ('<Operaciones>', 'muerto'): ['<Aux-log>', '<lit-gato>'],
    ('<Operaciones>', 'vivo'): ['<Aux-log>', '<lit-gato>'],
    ('<Operaciones>', 'minimo'): ['<Operando-creat>', '<Aux-Op-creativa>', '<Operando-creat>'],
    ('<Operaciones>', 'bajo'): ['<Operando-creat>', '<Aux-Op-creativa>', '<Operando-creat>'],
    ('<Operaciones>', 'medio'): ['<Operando-creat>', '<Aux-Op-creativa>', '<Operando-creat>'],
    ('<Operaciones>', 'alto'): ['<Operando-creat>', '<Aux-Op-creativa>', '<Operando-creat>'],
    ('<Operaciones>', 'maximo'): ['<Operando-creat>', '<Aux-Op-creativa>', '<Operando-creat>'],
    ('<Operaciones>', '{'): ['<Operando-conj>', '<Op-conj>', '<Operando-conj>'],
    ('<Operaciones>', 'conejo?'): ['<Operando-car>', 'conejo?'],
    ('<Operaciones>', 'lobo?'): ['<Operando-car>', 'lobo?'],
    ('<Operaciones>', 'Salvaje'): ['<Operando-car>', 'Salvaje'],
    ('<Operaciones>', 'Docil'): ['<Operando-car>', 'Docil'],
    ('<Operaciones>', 'escamas'): ['<Operando-str>', 'escamas'],
    ('<Operaciones>', 'acechar'): ['<Operando-creat>', 'acechar'],
    ('<Operaciones>', 'desolado?'): ['<Operando-conj>', 'desolado?'],
    ('<Operaciones>', 'calmar'): ['<Operando-creat>', 'calmar'],
    ('<Operaciones>', 'amenaza'): ['<Operando-creat>', 'amenaza'],
    ('<Operaciones>', 'Id_Op_Aritmetico'): ['<Aux-Arit>', 'Id_Op_Aritmetico', 240],
    ('<Operaciones>', 'Id_Op_Logico'): ['<Aux-log>', 'Id_Op_Logico', 240],
    ('<Operaciones>', 'Id_Op_Str'): ['<Aux-Strings-1>', '<Operando-str>'],
    ('<Operaciones>', 'Id_Op_Conj'): ['<Operando-conj>', '<Op-conj>', '<Operando-conj>'],
    ('<Operaciones>', 'Id_Op_Com'): ['<Comparacion>'],
    ('<Operaciones>', 'Id_Op_Creat'): ['<Operando-creat>', '<Aux-Op-creativa>', '<Operando-creat>'],
    ('<Inicio_parent_Aux>', '('): ['<Arit_Log>', ')', '<Inicio_parent_Aux>', '('],
    ('<Inicio_parent_Aux>', 'lit-oveja'): ['<Aux-Arit>', 'lit-oveja'],
    ('<Inicio_parent_Aux>', 'muerto'): ['<Aux-log>', '<lit-gato>'],
    ('<Inicio_parent_Aux>', 'vivo'): ['<Aux-log>', '<lit-gato>'],
    ('<Inicio_parent_Aux>', 'Id_Op_Aritmetico'): ['<Aux-Arit>', 'Id_Op_Aritmetico', 240],
    ('<Inicio_parent_Aux>', 'Id_Op_Logico'): ['<Aux-log>', 'Id_Op_Logico', 240],
    ('<Arit_Log>', '~'): ['epsilon'],
    ('<Arit_Log>', ')'): ['epsilon'],
    ('<Arit_Log>', 'plancton'): ['epsilon'],
    ('<Arit_Log>', 'atrae'): ['epsilon'],
    ('<Arit_Log>', 'repele'): ['epsilon'],
    ('<Arit_Log>', 'boa'): ['<Aux-Arit>'],
    ('<Arit_Log>', 'can'): ['<Aux-Arit>'],
    ('<Arit_Log>', 'emu'): ['<Aux-Arit>'],
    ('<Arit_Log>', 'gnu'): ['<Aux-Arit>'],
    ('<Arit_Log>', 'yak'): ['<Aux-Arit>'],
    ('<Arit_Log>', '>>'): ['<Aux-Arit>'],
    ('<Arit_Log>', 'sim'): ['<Aux-log>'],
    ('<Arit_Log>', 'mut'): ['<Aux-log>'],
    ('<Arit_Log>', 'dep'): ['<Aux-log>'],
    ('<Arit_Log>', 'com'): ['<Aux-log>'],
    ('<Llamada-func>', 'Id_Func'): ['~', ')', '<Parametros-real>', '(', 'Id_Func'],
    ('<Parametros-real>', 'lit-oveja'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'lit-huella'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'lit-serpiente'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'muerto'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'vivo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'minimo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'bajo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'medio'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'alto'): ['<Parametro-real>', '<Literales>'],
    ('<Parametros-real>', 'maximo'): ['<Parametro-real>', '<Literales>'],
    ('<Parametro-real>', ')'): ['epsilon'],
    ('<Parametro-real>', ','): ['<Parametro-real>', '<Literales>', ','],
    ('<Aritmeticas>', '('): ['<Aux-Arit>', '<Operando-arit>'],
    ('<Aritmeticas>', 'lit-oveja'): ['<Aux-Arit>', '<Operando-arit>'],
    ('<Aritmeticas>', 'Id_Op_Aritmetico'): ['<Aux-Arit>', '<Operando-arit>'],
    ('<Aux-Arit>', 'boa'): ['<Operando-arit>', '<Op-asignacion>'],
    ('<Aux-Arit>', 'can'): ['<Operando-arit>', '<Op-asignacion>'],
    ('<Aux-Arit>', 'emu'): ['<Operando-arit>', '<Op-asignacion>'],
    ('<Aux-Arit>', 'gnu'): ['<Operando-arit>', '<Op-asignacion>'],
    ('<Aux-Arit>', 'yak'): ['<Operando-arit>', '<Op-asignacion>'],
    ('<Aux-Arit>', '>>'): ['<lit-peligro>', '>>'],
    ('<Operando-arit>', '('): [')', '<Aritmeticas>', '('],
    ('<Operando-arit>', 'lit-oveja'): ['lit-oveja'],
    ('<Operando-arit>', 'Id_Op_Aritmetico'): ['Id_Op_Aritmetico', 240],
    ('<Operando-car>', 'lit-huella'): ['lit-huella'],
    ('<Operando-car>', 'Id_Op_Caracter'): ['Id_Op_Caracter', 240],
    ('<Logicas>', '('): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Logicas>', 'muerto'): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Logicas>', 'vivo'): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Logicas>', 'Id_Op_Logico'): ['<Operando-log>', '<Op-Log>', '<Operando-log>'],
    ('<Aux-log>', 'sim'): ['<Operando-log>', '<Op-Log>'],
    ('<Aux-log>', 'mut'): ['<Operando-log>', '<Op-Log>'],
    ('<Aux-log>', 'dep'): ['<Operando-log>', '<Op-Log>'],
    ('<Aux-log>', 'com'): ['<Operando-log>', '<Op-Log>'],
    ('<Operando-log>', '('): [')', '<Logicas>', '('],
    ('<Operando-log>', 'muerto'): ['<lit-gato>'],
    ('<Operando-log>', 'vivo'): ['<lit-gato>'],
    ('<Operando-log>', 'Id_Op_Logico'): ['Id_Op_Logico', 240],
    ('<Op-Log>', 'sim'): ['sim'],
    ('<Op-Log>', 'mut'): ['mut'],
    ('<Op-Log>', 'dep'): ['dep'],
    ('<Op-Log>', 'com'): ['com'],
    ('<Aux-Strings-1>', 'enroscar'): ['<Operando-str>', '<Operando-str>', 'enroscar'],
    ('<Aux-Strings-1>', 'mudar'): ['lit-oveja', 'piel', 'lit-oveja', 'mudar'],
    ('<Aux-Strings-1>', 'machetear'): ['lit-oveja', 'trozo', 'lit-oveja', 'machetear'],
    ('<Aux-Strings-1>', 'acechar'): ['<Operando-str>', 'acechar'],
    ('<Operando-str>', 'lit-serpiente'): ['lit-serpiente'],
    ('<Operando-str>', 'Id_Op_Str'): ['Id_Op_Str', 240],
    ('<Op-conj>', 'abeja'): ['abeja'],
    ('<Op-conj>', 'aguijon'): ['aguijon'],
    ('<Op-conj>', 'enjambre'): ['enjambre'],
    ('<Op-conj>', 'miel'): ['miel'],
    ('<Op-conj>', 'familia'): ['familia'],
    ('<Operando-conj>', '{'): ['<Lit-Colmena>'],
    ('<Operando-conj>', 'Id_Op_Conj'): ['Id_Op_Conj', 240],
    ('<Comparacion>', 'lit-huella'): ['<Operando-com>', '<Op-com>', 'lit-huella'],
    ('<Comparacion>', 'Id_Op_Com'): ['<Operando-com>', '<Op-com>', 'Id_Op_Com', 240],
    ('<Comparacion-2>', '('): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'lit-oveja'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'lit-huella'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'lit-serpiente'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'muerto'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'vivo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'minimo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'bajo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'medio'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'alto'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'maximo'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Comparacion-2>', 'Id_Op_Com'): ['<Operando-com>', '<Op-com>', '<Operando-com>'],
    ('<Operando-com>', '('): [')', '<Aux-Operando-com>', '('],
    ('<Operando-com>', 'lit-oveja'): ['<Literales>'],
    ('<Operando-com>', 'lit-huella'): ['<Literales>'],
    ('<Operando-com>', 'lit-serpiente'): ['<Literales>'],
    ('<Operando-com>', 'muerto'): ['<Literales>'],
    ('<Operando-com>', 'vivo'): ['<Literales>'],
    ('<Operando-com>', 'minimo'): ['<Literales>'],
    ('<Operando-com>', 'bajo'): ['<Literales>'],
    ('<Operando-com>', 'medio'): ['<Literales>'],
    ('<Operando-com>', 'alto'): ['<Literales>'],
    ('<Operando-com>', 'maximo'): ['<Literales>'],
    ('<Operando-com>', 'Id_Op_Com'): ['Id_Op_Com', 240],
    ('<Aux-Operando-com>', '('): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'lit-oveja'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'lit-huella'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'lit-serpiente'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'muerto'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'vivo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'minimo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'bajo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'medio'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'alto'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'maximo'): ['<Comparacion-2>'],
    ('<Aux-Operando-com>', 'Id_Op_Com'): ['<Comparacion-2>'],
    ('<Op-com>', 'presa'): ['presa'],
    ('<Op-com>', 'depredador'): ['depredador'],
    ('<Op-com>', 'clon'): ['clon'],
    ('<Op-com>', 'presaclon'): ['presaclon'],
    ('<Op-com>', 'depredadorclon'): ['depredadorclon'],
    ('<Op-com>', 'hibrido'): ['hibrido'],
    ('<Aux-Op-creativa>', 'alfa'): ['alfa'],
    ('<Aux-Op-creativa>', 'omega'): ['omega'],
    ('<Operando-creat>', 'minimo'): ['<lit-peligro>'],
    ('<Operando-creat>', 'bajo'): ['<lit-peligro>'],
    ('<Operando-creat>', 'medio'): ['<lit-peligro>'],
    ('<Operando-creat>', 'alto'): ['<lit-peligro>'],
    ('<Operando-creat>', 'maximo'): ['<lit-peligro>'],
    ('<Operando-creat>', 'Id_Op_Creat'): ['Id_Op_Creat', 240],
}
